In [1]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
# define data
df = load_iris()
X=df.data
y=df.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 50, test_size = 0.25)

In [4]:
# define min max scaler
#X_scaled = X_std * (max - min) + min
scaler = MinMaxScaler()

In [5]:
X_train=scaler.fit_transform(X_train)

In [6]:
X_test=scaler.transform(X_test)

In [7]:


print(X_train)

[[0.32352941 0.41666667 0.61403509 0.58333333]
 [0.20588235 0.58333333 0.0877193  0.04166667]
 [0.05882353 0.125      0.05263158 0.08333333]
 [0.17647059 0.16666667 0.40350877 0.375     ]
 [0.64705882 0.41666667 0.84210526 0.875     ]
 [0.02941176 0.375      0.07017544 0.04166667]
 [0.82352941 0.41666667 0.85964912 0.83333333]
 [0.23529412 0.625      0.07017544 0.08333333]
 [0.02941176 0.5        0.05263158 0.04166667]
 [0.41176471 0.75       0.12280702 0.08333333]
 [0.58823529 0.20833333 0.70175439 0.75      ]
 [0.44117647 0.33333333 0.71929825 0.95833333]
 [0.67647059 0.41666667 0.59649123 0.54166667]
 [0.32352941 0.79166667 0.12280702 0.125     ]
 [0.41176471 1.         0.0877193  0.125     ]
 [0.52941176 0.375      0.64912281 0.54166667]
 [0.44117647 0.29166667 0.71929825 0.75      ]
 [0.41176471 0.33333333 0.54385965 0.5       ]
 [0.79411765 0.5        0.64912281 0.54166667]
 [0.26470588 0.625      0.0877193  0.04166667]
 [0.02941176 0.41666667 0.05263158 0.04166667]
 [1.         

In [8]:
print(X_test)

[[0.38235294 0.41666667 0.54385965 0.5       ]
 [0.58823529 0.20833333 0.68421053 0.58333333]
 [0.32352941 0.58333333 0.12280702 0.04166667]
 [0.32352941 0.79166667 0.05263158 0.125     ]
 [0.64705882 0.41666667 0.73684211 0.79166667]
 [0.70588235 0.45833333 0.80701754 0.95833333]
 [0.41176471 0.20833333 0.70175439 0.79166667]
 [0.23529412 0.54166667 0.12280702 0.16666667]
 [0.14705882 0.41666667 0.07017544 0.        ]
 [0.55882353 0.08333333 0.61403509 0.58333333]
 [0.23529412 0.58333333 0.0877193  0.04166667]
 [0.91176471 0.33333333 0.89473684 0.75      ]
 [0.17647059 0.45833333 0.0877193  0.04166667]
 [0.73529412 0.41666667 0.78947368 0.83333333]
 [0.41176471 0.33333333 0.61403509 0.5       ]
 [0.20588235 0.41666667 0.10526316 0.04166667]
 [0.44117647 0.29166667 0.50877193 0.45833333]
 [0.29411765 0.70833333 0.0877193  0.04166667]
 [0.35294118 0.16666667 0.47368421 0.375     ]
 [0.70588235 0.41666667 0.70175439 0.66666667]
 [0.58823529 0.54166667 0.87719298 1.        ]
 [0.35294118 