In [16]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [17]:
df = load_iris()#cargo iris

In [18]:

print(df) #imprimo todo

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [19]:
X=df.data
print(X)#cojo solo los datos

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [20]:
y=df.target
print(y)#cojo la clase

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [21]:
#Separo los datos de "train" en entrenamiento y prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 50, test_size = 0.25)
#imprimos las formas que tienen
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
print(type(X_train))
print(type(X_test))
print(type(y_train))
print(type(y_test))

(112, 4)
(38, 4)
(112,)
(38,)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
st=StandardScaler()
#z = (x - media) / devst.  media=0 y devst=1

In [24]:
print("X_train antes:")
print(X_train)

X_train antes:
[[5.4 3.  4.5 1.5]
 [5.  3.4 1.5 0.2]
 [4.5 2.3 1.3 0.3]
 [4.9 2.4 3.3 1. ]
 [6.5 3.  5.8 2.2]
 [4.4 2.9 1.4 0.2]
 [7.1 3.  5.9 2.1]
 [5.1 3.5 1.4 0.3]
 [4.4 3.2 1.3 0.2]
 [5.7 3.8 1.7 0.3]
 [6.3 2.5 5.  1.9]
 [5.8 2.8 5.1 2.4]
 [6.6 3.  4.4 1.4]
 [5.4 3.9 1.7 0.4]
 [5.7 4.4 1.5 0.4]
 [6.1 2.9 4.7 1.4]
 [5.8 2.7 5.1 1.9]
 [5.7 2.8 4.1 1.3]
 [7.  3.2 4.7 1.4]
 [5.2 3.5 1.5 0.2]
 [4.4 3.  1.3 0.2]
 [7.7 2.8 6.7 2. ]
 [7.7 3.8 6.7 2.2]
 [6.4 2.9 4.3 1.3]
 [6.3 2.9 5.6 1.8]
 [5.  3.5 1.3 0.3]
 [4.9 3.6 1.4 0.1]
 [6.5 3.  5.5 1.8]
 [6.  2.9 4.5 1.5]
 [5.  3.6 1.4 0.2]
 [5.5 2.3 4.  1.3]
 [5.1 3.8 1.9 0.4]
 [7.3 2.9 6.3 1.8]
 [6.4 3.1 5.5 1.8]
 [6.7 3.1 4.4 1.4]
 [6.4 2.8 5.6 2.1]
 [5.6 2.5 3.9 1.1]
 [4.6 3.2 1.4 0.2]
 [6.3 2.3 4.4 1.3]
 [5.2 4.1 1.5 0.1]
 [5.5 2.5 4.  1.3]
 [6.9 3.1 4.9 1.5]
 [4.7 3.2 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [5.9 3.  4.2 1.5]
 [4.9 3.  1.4 0.2]
 [6.  2.7 5.1 1.6]
 [4.8 3.  1.4 0.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.9 1.8]
 [7.2 3.  5.8 1.6]
 [7.7 3.  6.1 2.

In [25]:
X_train=st.fit_transform(X_train)

In [26]:
print("X_train despues:")
print(X_train)

X_train despues:
[[-0.47968373 -0.16386268  0.45844398  0.42756946]
 [-0.96698149  0.76538393 -1.24739408 -1.28270837]
 [-1.5761037  -1.79004426 -1.36111661 -1.15114853]
 [-1.08880594 -1.55773261 -0.22389124 -0.23022971]
 [ 0.86038511 -0.16386268  1.19764047  1.34848828]
 [-1.69792814 -0.39617434 -1.30425534 -1.28270837]
 [ 1.59133175 -0.16386268  1.25450173  1.21692845]
 [-0.84515705  0.99769559 -1.30425534 -1.15114853]
 [-1.69792814  0.30076062 -1.36111661 -1.28270837]
 [-0.11421041  1.69463055 -1.13367154 -1.15114853]
 [ 0.61673623 -1.32542096  0.74275032  0.95380878]
 [ 0.00761403 -0.62848599  0.79961159  1.61160795]
 [ 0.98220955 -0.16386268  0.40158271  0.29600962]
 [-0.47968373  1.9269422  -1.13367154 -1.0195887 ]
 [-0.11421041  3.08850047 -1.24739408 -1.0195887 ]
 [ 0.37308735 -0.39617434  0.57216651  0.29600962]
 [ 0.00761403 -0.86079765  0.79961159  0.95380878]
 [-0.11421041 -0.62848599  0.2309989   0.16444979]
 [ 1.46950731  0.30076062  0.57216651  0.29600962]
 [-0.72333261 

In [27]:
print("X_test antes:")
print(X_test)

X_test antes:
[[5.6 3.  4.1 1.3]
 [6.3 2.5 4.9 1.5]
 [5.4 3.4 1.7 0.2]
 [5.4 3.9 1.3 0.4]
 [6.5 3.  5.2 2. ]
 [6.7 3.1 5.6 2.4]
 [5.7 2.5 5.  2. ]
 [5.1 3.3 1.7 0.5]
 [4.8 3.  1.4 0.1]
 [6.2 2.2 4.5 1.5]
 [5.1 3.4 1.5 0.2]
 [7.4 2.8 6.1 1.9]
 [4.9 3.1 1.5 0.2]
 [6.8 3.  5.5 2.1]
 [5.7 2.8 4.5 1.3]
 [5.  3.  1.6 0.2]
 [5.8 2.7 3.9 1.2]
 [5.3 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.7 3.  5.  1.7]
 [6.3 3.3 6.  2.5]
 [5.5 2.4 3.8 1.1]
 [5.8 4.  1.2 0.2]
 [7.9 3.8 6.4 2. ]
 [6.7 3.1 4.7 1.5]
 [7.7 2.6 6.9 2.3]
 [6.3 3.3 4.7 1.6]
 [6.5 2.8 4.6 1.5]
 [6.2 2.9 4.3 1.3]
 [6.8 3.2 5.9 2.3]
 [7.2 3.2 6.  1.8]
 [5.1 2.5 3.  1.1]
 [6.1 2.8 4.7 1.2]
 [6.7 3.3 5.7 2.5]
 [5.1 3.7 1.5 0.4]
 [4.6 3.1 1.5 0.2]
 [5.2 2.7 3.9 1.4]
 [6.  2.2 5.  1.5]]


In [28]:
X_test=st.transform(X_test)

In [29]:
print("X_test despues:")
print(X_test)

X_test despues:
[[-0.23603485 -0.16386268  0.2309989   0.16444979]
 [ 0.61673623 -1.32542096  0.68588905  0.42756946]
 [-0.47968373  0.76538393 -1.13367154 -1.28270837]
 [-0.47968373  1.9269422  -1.36111661 -1.0195887 ]
 [ 0.86038511 -0.16386268  0.85647286  1.08536862]
 [ 1.10403399  0.06844897  1.08391793  1.61160795]
 [-0.11421041 -1.32542096  0.74275032  1.08536862]
 [-0.84515705  0.53307228 -1.13367154 -0.88802887]
 [-1.21063038 -0.16386268 -1.30425534 -1.4142682 ]
 [ 0.49491179 -2.02235592  0.45844398  0.42756946]
 [-0.84515705  0.76538393 -1.24739408 -1.28270837]
 [ 1.95680507 -0.62848599  1.36822427  0.95380878]
 [-1.08880594  0.06844897 -1.24739408 -1.28270837]
 [ 1.22585843 -0.16386268  1.02705666  1.21692845]
 [-0.11421041 -0.62848599  0.45844398  0.16444979]
 [-0.96698149 -0.16386268 -1.19053281 -1.28270837]
 [ 0.00761403 -0.86079765  0.11727637  0.03288996]
 [-0.60150817  1.46231889 -1.24739408 -1.28270837]
 [-0.35785929 -1.55773261  0.00355383 -0.23022971]
 [ 1.10403399 -

In [30]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()#escojo el algoritmo
clf.fit(X_train,y_train)#lo entreno

DecisionTreeClassifier()

In [15]:
y_pred = clf.predict(X_test)# hago la prediccion

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
sc=accuracy_score(y_pred,y_test)
print(sc)

0.9473684210526315


In [33]:
print("en y_test hay:")
print(y_test)
print("en y_pred hay:")
print(y_test)
#estos no hace falta estandarizrlos porque son clases

en y_test hay:
[1 1 0 0 2 2 2 0 0 1 0 2 0 2 1 0 1 0 1 1 2 1 0 2 1 2 1 1 1 2 2 1 1 2 0 0 1
 2]
en y_pred hay:
[1 1 0 0 2 2 2 0 0 1 0 2 0 2 1 0 1 0 1 1 2 1 0 2 1 2 1 1 1 2 2 1 1 2 0 0 1
 2]
