In [2]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
digits=datasets.load_digits()
#este conjunto de datos tiene 1797 8x8 imagenes. cada imagen es un digito escrito a mano. 
#para utilizar la figura de 8x8 tenemos que transformarlo en un vector de 64

In [3]:
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'frame': None, 'feature_names': ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', '

In [4]:
aux=(digits.images)

In [5]:
print(aux)
# se pone cada fila de 64 en una matriz de 8x8 donde cada posicion es el valor para ese sitio de la imagen

[[[ 0.  0.  5. ...  1.  0.  0.]
  [ 0.  0. 13. ... 15.  5.  0.]
  [ 0.  3. 15. ... 11.  8.  0.]
  ...
  [ 0.  4. 11. ... 12.  7.  0.]
  [ 0.  2. 14. ... 12.  0.  0.]
  [ 0.  0.  6. ...  0.  0.  0.]]

 [[ 0.  0.  0. ...  5.  0.  0.]
  [ 0.  0.  0. ...  9.  0.  0.]
  [ 0.  0.  3. ...  6.  0.  0.]
  ...
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  0. ... 10.  0.  0.]]

 [[ 0.  0.  0. ... 12.  0.  0.]
  [ 0.  0.  3. ... 14.  0.  0.]
  [ 0.  0.  8. ... 16.  0.  0.]
  ...
  [ 0.  9. 16. ...  0.  0.  0.]
  [ 0.  3. 13. ... 11.  5.  0.]
  [ 0.  0.  0. ... 16.  9.  0.]]

 ...

 [[ 0.  0.  1. ...  1.  0.  0.]
  [ 0.  0. 13. ...  2.  1.  0.]
  [ 0.  0. 16. ... 16.  5.  0.]
  ...
  [ 0.  0. 16. ... 15.  0.  0.]
  [ 0.  0. 15. ... 16.  0.  0.]
  [ 0.  0.  2. ...  6.  0.  0.]]

 [[ 0.  0.  2. ...  0.  0.  0.]
  [ 0.  0. 14. ... 15.  1.  0.]
  [ 0.  4. 16. ... 16.  7.  0.]
  ...
  [ 0.  0.  0. ... 16.  2.  0.]
  [ 0.  0.  4. ... 16.  2.  0.]
  [ 0.  0.  5. ... 12.  0.  

In [6]:
print(digits.images.shape[0])
print(digits.images.shape[1])
print(digits.images.shape[2])
digits.images=digits.images.reshape(digits.images.shape[0],digits.images.shape[1]*digits.images.shape[2])
#es un array tridimensional,obtengo el tamano de cada <dimension>,1797 filas,cada imagen tiene el conjunto de datos
# con 8 filas cada imagen y 8 columnas cada fila


1797
8
8


In [9]:
print(digits.target)

[0 1 2 ... 8 9 8]


In [10]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test,y_train,y_test=train_test_split(digits.images,digits.target,test_size=0.20)
#separa en subconjuntos

In [14]:
#aplico standard scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

#ambas x
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [15]:
#aplico con 5 vecinos de prueba
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)
#x,y de train

KNeighborsClassifier()

In [16]:
y_pred = classifier.predict(x_test)
#x de test

In [17]:
#hago la matriz de confusion para evaluar el rendimiento del modelo
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[27  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  0]
 [ 0  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 39  0  0  0  0  0  0]
 [ 0  0  0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0 38  1  0  0  1]
 [ 0  0  0  0  0  0 30  0  0  0]
 [ 0  0  0  0  0  0  0 35  0  1]
 [ 0  3  0  0  0  0  0  0 36  0]
 [ 0  0  0  0  0  1  0  0  0 37]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        27
           1       0.92      1.00      0.96        34
           2       1.00      1.00      1.00        36
           3       1.00      1.00      1.00        39
           4       1.00      1.00      1.00        41
           5       0.97      0.95      0.96        40
           6       0.97      1.00      0.98        30
           7       1.00      0.97      0.99        36
           8       1.00      0.92      0.96        39
           9       0.95      0.97      0.96        38

    accuracy                           0.98       360
   macro avg       

In [18]:
error = []

#aplico los diferentes numeros de vecinos
for i in range(1, 16):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train, y_train)
    pred_i = knn.predict(x_test)
    error.append(np.mean(pred_i != y_test))

In [21]:
#print((pred_i != y_test))  : false false true   mean calcula la media

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False  True False False False False
 False False False False False False False False  T

In [20]:
print(error)

[0.022222222222222223, 0.030555555555555555, 0.030555555555555555, 0.019444444444444445, 0.019444444444444445, 0.022222222222222223, 0.019444444444444445, 0.022222222222222223, 0.022222222222222223, 0.025, 0.019444444444444445, 0.027777777777777776, 0.03333333333333333, 0.03333333333333333, 0.03333333333333333]


In [ ]:
etiquetas=["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15"]

In [ ]:
co=np.arange(len(error))
an=0.3

In [ ]:
#creo el grafico
fig,ax=plt.subplots()
ax.bar(co,error,an)
ax.set_title("grafico de error para k vecinos de 1 a 15")
ax.set_ylabel("numeros")
ax.set_xticks(co)
ax.set_xticklabels(etiquetas)

In [ ]:
print(type(digits.images))
#para ver de que tipo es, porque estaba cogiendo digits con el argumento as_frame y en digits.data aplicaba replace
#para cambiar los numeros mayores que 1 por 1, pero digits.data es un dataframe y para aplicar kvecinos 
# en el ejemplo basico sin modificar estos 1 lo hace sobre un array de numpy

In [ ]:
digits.images=np.clip(digits.images,0,1)
print(digits.images)
#los kvecinos lo aplico sobre digits.images que es un array de numpy, para modificar estos arrays tengo que aplicar
#la funcion clip
#out_array = np.clip(in_array, a_min = 2, a_max = 6)
#Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
#Output array :  [2 2 3 4 5 6 6 6]

In [ ]:
#esto es lo mismo que en el ejemplo normal sin modificar los 1
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test,y_train,y_test=train_test_split(digits.images,digits.target,test_size=0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:
error1 = []


for i in range(1, 16):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train, y_train)
    pred_i = knn.predict(x_test)
    error1.append(np.mean(pred_i != y_test))

In [ ]:
print(error1)

In [ ]:
co=np.arange(len(error1))
an=0.3

In [ ]:
#creo el grafico
fig,ax=plt.subplots()
ax.bar(co,error1,an)
ax.set_title("grafico de error para k vecinos de 1 a 15 con bits")
ax.set_ylabel("numeros")
ax.set_xticks(co)
ax.set_xticklabels(etiquetas)