In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.patches as mpatches
import seaborn as sb



from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [3]:
dataframe = pd.read_csv("reviews_sentiment.csv",sep=';')
dataframe.head(10)

Review Title  \
0                Sin conexión   
1                faltan cosas   
2  Es muy buena lo recomiendo   
3             Version antigua   
4                   Esta bien   
5                       Buena   
6               De gran ayuda   
7                   Muy buena   
8                Ta to guapa.   
9            Se han corregido   

                                         Review Text  wordcount  \
0  Hola desde hace algo más de un mes me pone sin...         23   
1                 Han mejorado la apariencia pero no         20   
2                               Andres e puto amoooo          4   
3  Me gustana mas la version anterior esta es mas...         17   
4                    Sin ser la biblia.... Esta bien          6   
5        Nada del otro mundo pero han mejorado mucho          8   
6   Lo malo q necesita de …,pero la app es muy buena         23   
7  Estaba más acostumbrado al otro diseño, pero e...         16   
8                                    Va de escándalo         21   
9  Han corregido muchos fallos pero el diseño es ...         13   

  titleSentiment textSentiment  Star Rating  sentimentValue  
0       negative      negative            1       -0.486389  
1       negative      negative            1       -0.586187  
2            NaN      negative            1       -0.602240  
3            NaN      negative            1       -0.616271  
4       negative      negative            1       -0.651784  
5       positive      negative            1       -0.720443  
6       positive      negative            1       -0.726825  
7       positive      negative            1       -0.736769  
8       positive      negative            1       -0.765284  
9       negative      negative            1       -0.797961

In [4]:
dataframe.describe()

wordcount  Star Rating  sentimentValue
count  257.000000   257.000000      257.000000
mean    11.501946     3.420233        0.383849
std     13.159812     1.409531        0.897987
min      1.000000     1.000000       -2.276469
25%      3.000000     3.000000       -0.108144
50%      7.000000     3.000000        0.264091
75%     16.000000     5.000000        0.808384
max    103.000000     5.000000        3.264579

In [5]:
print(dataframe.groupby('Star Rating').size())#agrupo por atributo y cuento

Star Rating
1    37
2    24
3    78
4    30
5    88
dtype: int64


In [6]:
X = dataframe[['wordcount','sentimentValue']].values
y = dataframe['Star Rating'].values



In [10]:
from sklearn.metrics import accuracy_score

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
n_neighbors = 7

knn = KNeighborsClassifier(n_neighbors)
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=7)

In [23]:
pred = knn.predict(X_test)
print(confusion_matrix(y_test, pred))
print(classification_report(y_test, pred))

[[ 9  0  1  0  0]
 [ 0  1  0  0  0]
 [ 0  1 17  0  1]
 [ 0  0  2  8  0]
 [ 0  0  4  0 21]]
              precision    recall  f1-score   support

           1       1.00      0.90      0.95        10
           2       0.50      1.00      0.67         1
           3       0.71      0.89      0.79        19
           4       1.00      0.80      0.89        10
           5       0.95      0.84      0.89        25

    accuracy                           0.86        65
   macro avg       0.83      0.89      0.84        65
weighted avg       0.89      0.86      0.87        65



In [24]:
(knn.score(X_train, y_train))


0.8958333333333334

In [25]:
accuracy_score(y_test, pred)

0.8615384615384616

In [27]:
pred = knn.predict(X_train)
accuracy_score(y_train, pred)

0.8958333333333334

In [29]:
print(knn.predict([[5, 1.0]]))


[2]
