In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
#pd.leercsv
dataset=pd.read_csv("SocialNetworkAds.csv")

In [3]:
print(dataset)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


In [5]:
x=dataset.iloc[:,[2,3]].values#age y salario
y=dataset.iloc[:,4].values#purchased
#se cogen sin etiquetas
#columna 2 y 3

In [6]:
print("en x tengo:")
print(x)
print(x.shape)
print(type(x))

en x tengo:
[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [

In [7]:
print("en y tengo:")
print(y)
print(y.shape)
print(type(y))

en y tengo:
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]
(400,)
<class 'numpy.ndarray'>


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
#separo en conjunto de entrenamiento y de test
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [10]:
print("para x_train:")
print(type(X_train))
print(len(X_train))
print(X_train.shape)
print("\n")
print("para x_test:")
print(type(X_test))
print(len(X_test))
print(X_test.shape)
print("\n")
print("para y_train:")
print(type(y_train))
print(len(y_train))
print(y_train.shape)
print("\n")
print("para y_test:")
print(type(y_test))
print(len(y_test))
print(y_test.shape)
print("\n")
print("para x:")
print(type(x))
print(len(x))
print(x.shape)
print("\n")
print("para y:")
print(type(y))
print(len(y))
print(y.shape)


para x_train:
<class 'numpy.ndarray'>
300
(300, 2)


para x_test:
<class 'numpy.ndarray'>
100
(100, 2)


para y_train:
<class 'numpy.ndarray'>
300
(300,)


para y_test:
<class 'numpy.ndarray'>
100
(100,)


para x:
<class 'numpy.ndarray'>
400
(400, 2)


para y:
<class 'numpy.ndarray'>
400
(400,)


In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#standarizar datos


In [12]:
print("x_train antes:")
print(X_train)
X_train=sc.fit_transform(X_train)




x_train antes:
[[    35  50000]
 [    32  86000]
 [    46  22000]
 [    37 144000]
 [    48  33000]
 [    49  36000]
 [    35 108000]
 [    47  43000]
 [    35  65000]
 [    28  85000]
 [    31  15000]
 [    42  79000]
 [    18  82000]
 [    38  71000]
 [    27  89000]
 [    29  61000]
 [    38  51000]
 [    20  82000]
 [    24  55000]
 [    40  72000]
 [    48  35000]
 [    39  79000]
 [    23  28000]
 [    41  51000]
 [    21  72000]
 [    26  72000]
 [    30  87000]
 [    20  74000]
 [    33 113000]
 [    40  47000]
 [    41  72000]
 [    38  55000]
 [    30 107000]
 [    27  88000]
 [    39 134000]
 [    32 117000]
 [    19  26000]
 [    49  65000]
 [    18  86000]
 [    32 117000]
 [    24  23000]
 [    40  75000]
 [    35  61000]
 [    30  80000]
 [    40  57000]
 [    39 106000]
 [    36  60000]
 [    60  83000]
 [    28  87000]
 [    27  20000]
 [    35  72000]
 [    29  47000]
 [    32  18000]
 [    43 112000]
 [    58  38000]
 [    26  16000]
 [    39  42000]
 [    33  51000]

In [13]:
print("x_train despues:")
print(X_train)

x_train despues:
[[-0.21586173 -0.55345795]
 [-0.50496226  0.54169519]
 [ 0.84417355 -1.40524372]
 [-0.02312804  2.30610858]
 [ 1.03690724 -1.07061359]
 [ 1.13327409 -0.97935083]
 [-0.21586173  1.21095544]
 [ 0.9405404  -0.76640439]
 [-0.21586173 -0.09714414]
 [-0.89042964  0.51127427]
 [-0.60132911 -1.61819016]
 [ 0.45870618  0.32874875]
 [-1.85409808  0.42001151]
 [ 0.0732388   0.08538138]
 [-0.98679648  0.63295795]
 [-0.7940628  -0.21882782]
 [ 0.0732388  -0.52303703]
 [-1.66136439  0.42001151]
 [-1.27589702 -0.40135334]
 [ 0.26597249  0.1158023 ]
 [ 1.03690724 -1.00977175]
 [ 0.16960565  0.32874875]
 [-1.37226386 -1.2227182 ]
 [ 0.36233933 -0.52303703]
 [-1.56499755  0.1158023 ]
 [-1.08316333  0.1158023 ]
 [-0.69769595  0.57211611]
 [-1.66136439  0.17664414]
 [-0.40859542  1.36306004]
 [ 0.26597249 -0.64472071]
 [ 0.36233933  0.1158023 ]
 [ 0.0732388  -0.40135334]
 [-0.69769595  1.18053452]
 [-0.98679648  0.60253703]
 [ 0.16960565  2.00189937]
 [-0.50496226  1.48474372]
 [-1.757731

In [14]:
print("x_test antes:")
print(X_test)
X_test=sc.transform(X_test)

x_test antes:
[[    21  68000]
 [    32  18000]
 [    29  83000]
 [    59  29000]
 [    27  90000]
 [    29  83000]
 [    41  79000]
 [    40  75000]
 [    36 118000]
 [    34  43000]
 [    60  42000]
 [    35  88000]
 [    56  60000]
 [    31  74000]
 [    44 139000]
 [    38  65000]
 [    45 131000]
 [    33  28000]
 [    42 108000]
 [    28  79000]
 [    24  32000]
 [    33 149000]
 [    21  16000]
 [    32 150000]
 [    47  30000]
 [    36 126000]
 [    37  75000]
 [    52 150000]
 [    38  50000]
 [    40 142000]
 [    38  59000]
 [    42  90000]
 [    58  23000]
 [    59  76000]
 [    24  84000]
 [    41  71000]
 [    37 146000]
 [    23  66000]
 [    24  55000]
 [    33  43000]
 [    22  27000]
 [    23  48000]
 [    31  76000]
 [    34  25000]
 [    40 107000]
 [    18  68000]
 [    30  62000]
 [    35  72000]
 [    36 144000]
 [    33  31000]
 [    41  72000]
 [    37  74000]
 [    30  15000]
 [    27  58000]
 [    38  61000]
 [    49  89000]
 [    36  52000]
 [    53  34000]


In [15]:
print("x_test despues:")
print(X_test)

x_test despues:
[[-1.56499755 -0.00588138]
 [-0.50496226 -1.5269274 ]
 [-0.7940628   0.45043243]
 [ 2.09694253 -1.19229727]
 [-0.98679648  0.66337887]
 [-0.7940628   0.45043243]
 [ 0.36233933  0.32874875]
 [ 0.26597249  0.20706507]
 [-0.11949489  1.51516464]
 [-0.31222858 -0.76640439]
 [ 2.19330937 -0.79682531]
 [-0.21586173  0.60253703]
 [ 1.807842   -0.24924874]
 [-0.60132911  0.17664414]
 [ 0.65143987  2.15400397]
 [ 0.0732388  -0.09714414]
 [ 0.74780671  1.91063661]
 [-0.40859542 -1.2227182 ]
 [ 0.45870618  1.21095544]
 [-0.89042964  0.32874875]
 [-1.27589702 -1.10103451]
 [-0.40859542  2.45821318]
 [-1.56499755 -1.58776924]
 [-0.50496226  2.4886341 ]
 [ 0.9405404  -1.16187635]
 [-0.11949489  1.75853201]
 [-0.02312804  0.20706507]
 [ 1.42237462  2.4886341 ]
 [ 0.0732388  -0.55345795]
 [ 0.26597249  2.24526673]
 [ 0.0732388  -0.27966966]
 [ 0.45870618  0.66337887]
 [ 2.00057568 -1.3748228 ]
 [ 2.09694253  0.23748599]
 [-1.27589702  0.48085335]
 [ 0.36233933  0.08538138]
 [-0.0231280

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
#defino el algoritmo a utilizar

classifier=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
#p=2 distancia euclidiana

In [18]:
#entreno el modelo
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [19]:
#hago una prediccion
y_pred=classifier.predict(X_test)


In [20]:
print("y_test tengo:")
print(y_test)

y_test tengo:
[0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 0 0 0 1 1
 1 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 1 1 0 0 1 0 1 0]


In [21]:
print("y_pred tengo:")
print(y_pred)

y_pred tengo:
[0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1
 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0 1
 1 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 1 0]


In [22]:
from sklearn.metrics import confusion_matrix

In [23]:
#matriz de confusion
cm=confusion_matrix(y_test,y_pred)#ambos y
print(cm)
#diagonal principal bien 
#5 que eran no purchased han sido puestos como purchased
#         prediccion 
#          no  si
#real no       X
#     si

[[56  2]
 [ 4 38]]
