In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.linear_model import LinearRegression, LogisticRegression

In [2]:
segment = pd.read_csv('convertido.csv')
segment.head()#cargo datos

region.centroid.col  region.centroid.row  region.pixel.count   
0                  218                  178                   9  \
1                  113                  130                   9   
2                  202                   41                   9   
3                   32                  173                   9   
4                   61                  197                   9   

   short.line.density.5  short.line.density.2  vedge.mean  vegde.sd   
0              0.111111                   0.0    0.833333  0.547722  \
1              0.000000                   0.0    0.277778  0.250924   
2              0.000000                   0.0    0.944448  0.772202   
3              0.000000                   0.0    1.722220  1.781590   
4              0.000000                   0.0    1.444440  1.515350   

   hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean   
0    1.111110  0.544331       59.629600      52.4444      75.22220  \
1    0.333333  0.365148        0.888889       0.0000       2.55556   
2    1.111110  1.025600      123.037000     111.8890     139.77800   
3    9.000000  6.749490       43.592600      39.5556      52.88890   
4    2.611110  1.925460       49.592600      44.2222      61.55560   

   rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean   
0      51.222200   -21.55560      46.7778     -25.22220    75.22220  \
1       0.111111    -2.66667       5.0000      -2.33333     2.55556   
2     117.444000   -33.44440      50.2222     -16.77780   139.77800   
3      38.333300   -12.11110      27.8889     -15.77780    52.88890   
4      43.000000   -16.11110      35.8889     -19.77780    61.55560   

   saturation.mean  hue.mean    class  
0         0.318996  -2.04055     path  
1         1.000000  -2.12325  foliage  
2         0.199347  -2.29992      sky  
3         0.266914  -1.99886     path  
4         0.302925  -2.02227     path

In [3]:
#minmaxscaler pone los datos entre 0 y 1
#standardscaler pone los datos para que tengan media 0 y desviacion estandar 1

In [4]:
target = segment['class'].copy()#cogemos la de la clase
features = segment.drop(['class'], axis=1)#cogemos predictoras eliminando clase

In [5]:
from sklearn.preprocessing import  LabelBinarizer
d = LabelBinarizer().fit(np.unique(target)).transform(target)#label fit unique transform
d = d.astype(float)
d

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [6]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()

In [7]:
x=st.fit_transform(features)

In [8]:
from sklearn.model_selection import train_test_split 
X_train, X_test, d_train, d_test = train_test_split(x, d, test_size = 0.33,stratify=target)#separamos

In [9]:
y_predict=np.ones(d_test.shape)



In [10]:
#recorro columnas de array de test
    #regresion lineal con lo que hay en xtrain y los valores de dtrain(1col) y muchas filas para la columna recorrida
    #guardo prediccion de las filas en la columna que corresponda sobre las muestras de test
#coge el maximo de cada fila

In [12]:
#FLPA
for i in range(d_test.shape[1]):#columnas
    regresion = LinearRegression().fit(X_train, d_train[:,i])#entreno en su posicion
    y_predict[:,i] = regresion.predict(X_test)#guardo preccion
y_predict_test = np.argmax(y_predict, axis=1)#vcojo el maximo

#predice cada casilla
print(y_predict_test)



[5 0 3 5 3 2 0 0 0 4 2 5 4 6 4 4 5 5 5 4 3 2 6 4 6 0 3 5 5 2 6 5 3 4 4 6 3
 1 4 5 4 3 0 3 4 5 6 6 3 3 0 1 2 6 0 2 4 6 2 2 6 4 4 4 1 6 3 6 3 6 5 2 5 0
 2 4 4 0 4 5 6 4 0 2 4 6 4 2 2 4 3 4 4 3 3 0 2 6 0 2 2 2 4 5 0 6 1 4 0 3 3
 2 0 6 5 3 0 0 2 2 2 2 6 2 5 0 4 0 0 2 2 2 3 0 0 5 4 6 1 1 5 4 5 0 6 3 1 2
 4 5 2 2 0 0 2 0 5 3 1 5 2 2 3 3 4 3 2 1 0 4 2 3 6 2 1 6 2 2 2 0 5 0 5 4 6
 3 3 5 4 2 6 1 2 5 0 3 6 2 2 3 5 4 0 2 0 4 2 2 6 5 0 3 1 4 6 1 1 4 3 6 3 2
 6 4 4 4 4 3 1 1 0 5 3 5 6 6 6 2 3 5 2 6 4 4 0 0 3 3 1 0 3 0 2 5 0 4 2 3 5
 3 6 5 3 0 0 1 6 1 5 2 0 3 2 3 5 0 0 5 3 5 2 4 2 0 3 3 5 2 0 3 0 0 0 0 4 4
 2 4 2 2 0 5 1 0 0 3 0 4 0 4 0 5 2 3 2 5 3 0 2 2 4 0 0 4 4 0 2 0 4 4 2 4 0
 5 5 5 2 6 3 6 0 2 3 2 0 5 5 2 2 6 5 3 1 3 1 3 3 2 4 6 2 3 4 6 0 3 1 1 5 3
 2 4 2 0 0 0 4 3 0 5 0 1 6 2 5 2 5 6 1 0 0 2 2 2 1 5 0 4 6 2 2 6 2 6 0 4 0
 0 5 0 4 5 1 2 4 2 4 0 5 6 5 4 6 3 4 6 3 2 0 3 4 5 5 3 3 0 3 4 5 6 2 5 0 3
 3 4 6 5 2 0 5 1 4 6 3 2 6 4 5 4 3 4 3 3 0 4 5 5 1 5 3 5 3 0 3 6 2 2 5 0 0
 2 6 1 0 3 5 2 0 6 0 1 5 

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print("Tasa de aciertos =", accuracy_score(np.argmax(d_test, axis=1), np.argmax(y_predict, axis=1)))

print("\nMatriz de Confusión:\n", confusion_matrix(np.argmax(d_test, axis=1), np.argmax(y_predict, axis=1)))

Tasa de aciertos = 0.854521625163827

Matriz de Confusión:
 [[107   0   2   0   0   0   0]
 [ 21  44   2   0  26   4  12]
 [  1   3  98   0   0   0   7]
 [  0   0   0 108   1   0   0]
 [  0   0   0   0 109   0   0]
 [  0   0   0   0   0 109   0]
 [  1   1  27   0   3   0  77]]


<h3>Validacion cruzada estratificada</h3>

In [13]:
from sklearn.model_selection import StratifiedKFold
K = 10
kfold = StratifiedKFold(n_splits=K)

In [14]:
#recorro cada train y test de cada particion
# de a 0 a 7
    #entreno con los entrenamiento y los de test para la columna seleccionada entre 0 a 7
    #guardo en las filas en la columna entre a 0 a 7 marcada la prediccion sobre test

In [19]:
from sklearn import preprocessing
clase=preprocessing.LabelEncoder()
clase.fit(np.unique(target))# guardo las etiqueitas
y_auxiliar=clase.transform(target)#transformo
target=y_auxiliar


In [20]:

#FYFLPA
aciertos = np.zeros(K, dtype=float)
k = 0
print("ACIERTOS\n")
for train_index, test_index in kfold.split(x,y_auxiliar):#recorro los separados: train,test
    
    y_test = np.zeros((len(test_index), 7), dtype=float)#matrriz con 0
    for i in range(7):
        regresion = LinearRegression().fit(x[train_index], d[train_index, i])#entreno con los 3. solo la comulna
        y_test[:,i] = regresion.predict(x[test_index])#guardo preccion
    
    aciertos[k] = accuracy_score(target[test_index], np.argmax(y_test, axis=1))# score con el maximo
    print(aciertos[k])
    k += 1
print("\n\nTasa de aciertos =", np.mean(aciertos))  

ACIERTOS

0.8917748917748918
0.8225108225108225
0.8441558441558441
0.8354978354978355
0.8701298701298701
0.8528138528138528
0.8225108225108225
0.8354978354978355
0.8311688311688312
0.8571428571428571


Tasa de aciertos = 0.8463203463203464


In [21]:
from sklearn.linear_model import LogisticRegression

In [22]:
regresion_logistica = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000).fit(x, target)

In [23]:
y_test = regresion_logistica.predict(X_test)
print("Tasa de aciertos =", accuracy_score(np.argmax(d_test, axis=1), y_test))#maximo

Tasa de aciertos = 0.9410222804718218


In [24]:
print("Matriz de Confusión:\n", confusion_matrix(np.argmax(d_test, axis=1), y_test))

Matriz de Confusión:
 [[108   0   0   0   0   0   1]
 [  1 103   0   0   1   0   4]
 [  0   2  92   0   0   0  15]
 [  0   0   0 109   0   0   0]
 [  0   0   0   0 109   0   0]
 [  0   0   0   0   0 109   0]
 [  0  10  11   0   0   0  88]]


In [25]:
#FLPA
aciertos = np.zeros(K, dtype=float)#tamano 10
k = 0
print("ACIERTOS\n")
for train_index, test_index in kfold.split(x, target):
    regresion_logistica = LogisticRegression(solver='lbfgs', multi_class='auto', max_iter=1000).fit(x[train_index], target[train_index])
    y_test = regresion_logistica.predict(x[test_index])#prediccion
    aciertos[k] = accuracy_score(target[test_index], y_test)#score
    print(aciertos[k])
    k += 1
print("\n\nTasa de aciertos =", np.mean(aciertos))

ACIERTOS

0.9567099567099567
0.9004329004329005
0.9437229437229437
0.9437229437229437
0.948051948051948
0.9393939393939394
0.9523809523809523
0.9090909090909091
0.922077922077922
0.9090909090909091


Tasa de aciertos = 0.9324675324675324
