In [1]:
# Import necessary libraries
import numpy as np

In [2]:
#Adaline neural network
def Adaline(Input, Target, lr=0.2, stop=0.001):
    weight = np.random.random(Input.shape[1])
    bias   = np.random.random(1)
    
    Error=[stop +1]
    # check the stop condition for the network
    while Error[-1] > stop or Error[-1]-Error[-2] > 0.0001:
        error = []
        for i in range(Input.shape[0]):
            Y_input = sum(weight*Input[i]) + bias
             
            # Update the weight
            for j in range(Input.shape[1]):
                weight[j]=weight[j] + lr*(Target[i]-Y_input)*Input[i][j]
 
            # Update the bias
            bias=bias + lr*(Target[i]-Y_input)
             
            # Store squared error value
            error.append((Target[i]-Y_input)**2)
        # Store sum of square errors
        Error.append(sum(error))
        print('Error :',Error[-1])
    return weight, bias

In [3]:
# Input dataset
x = np.array([[1.0, 1.0, 1.0],
              [1.0, -1.0, 1.0],
              [-1.0, 1.0, 1.0],
              [-1.0, -1.0, -1.0]])

In [4]:
# Target values
t = np.array([1, 1, 1, -1])

In [5]:
w,b = Adaline(x, t, lr=0.2, stop=0.001)
print('weight :',w)
print('Bias :',b)

Error : [3.5393319]
Error : [1.02986717]
Error : [0.67632673]
Error : [0.46666749]
Error : [0.32291874]
Error : [0.22348598]
Error : [0.15467191]
Error : [0.1070466]
Error : [0.07408568]
Error : [0.05127382]
Error : [0.035486]
Error : [0.02455944]
Error : [0.0169973]
Error : [0.01176363]
Error : [0.00814147]
Error : [0.00563461]
Error : [0.00389965]
Error : [0.0026989]
Error : [0.00186788]
Error : [0.00129274]
Error : [0.00089469]
weight : [0.01035625 0.01035625 0.98731624]
Bias : [0.01035625]


In [6]:
def prediction(X,w,b):
    y=[]
    for i in range(X.shape[0]):
        x = X[i]
        y.append(sum(w*x)+b)
    return y


In [7]:
prediction(x,w,b)

[array([1.01838499]),
 array([0.99767249]),
 array([0.99767249]),
 array([-0.99767249])]